# Generated by Django 4.2.3 on 2023-10-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookapplication',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
