# Generated by Django 4.2.3 on 2023-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bookapplication_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookapplication',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('ACCEPTED', 'Accepted'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected'), ('RETURNED', 'Returned')], default='REQUESTED', max_length=20),
        ),
    ]
